// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zwhcmjjvylcnsnslsxxr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3aGNtamp2eWxjbnNuc2xzeHhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4ODg3NzMsImV4cCI6MjA2ODQ2NDc3M30.hmYqAR4FDhrO-ZdkDMd-cOdFTFkbIlfGC5fRgl8k034";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});